<?php

/**
 * @file
 * Contains anoncontent.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function anoncontent_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the anoncontent module.
    case 'help.page.anoncontent':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Anonymous 12 Step Intergroup Default Content Export and Import') . '</p>';
      return $output;

    default:
  }
}

