<?php

/**
 * @file
 * Contains twelvestepmeetings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twelvestepmeetings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twelvestepmeetings module.
    case 'help.page.twelvestepmeetings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twelve Step Meetings Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function twelvestepmeetings_theme() {
  $theme = [];

  return $theme;
}
