<?php

/**
 * @file
 * Contains anonmeetings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function anonmeetings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the anonmeetings module.
    case 'help.page.anonmeetings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Anonymous 12 Step Meetings Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function anonmeetings_theme() {
  $theme = [];

  return $theme;
}
