<?php

/**
 * @file
 * Contains anonlocations.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function anonlocations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the anonlocations module.
    case 'help.page.anonlocations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Anonymous 12 Step Location Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function anonlocations_theme() {
  $theme = [];

  return $theme;
}
