<?php

/**
 * @file
 * Contains weeklytime.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weeklytime_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the weeklytime module.
    case 'help.page.weeklytime':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Weekly time field') . '</p>';
      return $output;

    default:
  }
}
