<?php

/**
 * @file
 * Contains twelvestephelper.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twelvestephelper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twelvestephelper module.
    case 'help.page.twelvestephelper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twelve Step Helper') . '</p>';
      return $output;

    default:
  }
}

