<?php
/**
 * Installation and update handlers for baltimoreaa migrate module.
 */

use Drupal\migrate\MigrateExecutable;
use Drupal\migrate\MigrateMessage;

/**
 * Implements hook_install().
 */
function baltimoreaa_migrate_install() {
  $migrations = \Drupal::service('plugin.manager.migration')
    ->createInstancesByTag('baltimoreaa');

  foreach ($migrations as $migration) {
    $executable = new MigrateExecutable($migration, new MigrateMessage());
    $executable->import();
  }
}
