<?php

/**
 * @file
 * Contains twelvestepgroups.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twelvestepgroups_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twelvestepgroups module.
    case 'help.page.twelvestepgroups':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twelve Step Group Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function twelvestepgroups_theme() {
  $theme = [];

  return $theme;
}
